### ISSUE TITLE
Update for new search-index API

### ISSUE THREAD

**Issue by fergiemcdowall** [eklem/search-index-cookbook#17]
Search API changed in 0.8.0 to allow for NOT and OR. Facets are now 'categories' and 'buckets'

Need to update the examples here

**Comment by eklem** [comment]
Changed the stuff that was deprecated, but haven't added so much OR/NOT-stuff, but that will come later.

**Comment by eklem** [comment]
Ah, not here: https://github.com/eklem/search-index-cookbook/blob/master/doc/reference/configuration.md
