### ISSUE TITLE
How to user 0 result queries to something positive: Synonyms

### ISSUE THREAD

**Issue by eklem** [eklem/search-index-cookbook#24]
Figure out which synonyms to add and how to do it wit OR-search
(expand search with more OR-queries, but boost the original query)

**Comment by fergiemcdowall** [comment]
https://github.com/NaturalNode/natural#stemmers

The general strategy would be to index stems on the way in, and then do a search for the search term and its stem.

**Comment by eklem** [comment]
I was more thinking about something like:
`car -> transportation`
When the user has one vocabulary, and the content/organization a different vocabulary.

**Comment by fergiemcdowall** [comment]
Sorry- yes, you are talking about synonyms and I am talking about stemming- doh!

**Comment by fergiemcdowall** [comment]
In a way, synonyms are easier to solve, because you just set up a query processor that substitutes in the synonym

```javascript
[
  {
    AND: {body: ['car', 'repair']}
  }
]
````

...transformation ('car' -> 'automobile')...

```javascript
[
  {
    AND: {body: ['car', 'repair']}
  },
  {
    AND: {body: ['automobile', 'repair']}
  }
]
````

**Comment by eklem** [comment]
And, you can get some clear indications that you need to add synonyms if you have logging on 0 results queries.

**Comment by eklem** [comment]
Could be cool to create a small synonyms module where you could connect a google drive spreadsheet with synonyms.

**Comment by eklem** [comment]
Just the layout for the [synonyms-module](https://github.com/eklem/search-index-synonyms).

**Comment by eklem** [comment]
Fixed with https://github.com/eklem/search-index-cookbook/commit/de1c9b61bb6016f3bbdfaa69a1b8770d580134be
